# Server properties
server:
  port: 8111

# Application metadata
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Profile Service - Local Instance

# Spring properties
spring:
  application:
    name: users-profile
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:../env/dev.properties
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.add.type.headers]": false
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.trusted.packages]": "com.mariuszilinskas.streamix.*"
        "[spring.json.value.default.type]": "com.mariuszilinskas.streamix.users.profile.event.UserRegisteredEvent"
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
 
# AWS properties
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_REGION}
    avatar-bucket-name: ${AWS_AVATAR_BUCKET_NAME}

# Service discovery properties
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# Messaging properties
kafka:
  topics:
    user-registered: ${KAFKA_USER_REGISTERED_TOPIC}
  groups:
    profile-registration: ${KAFKA_PROFILE_REGISTRATION_GROUP}

rabbitmq:
  queues:
    profile-setup: ${RMQ_PROFILE_SETUP_Q}
    delete-user-data: ${RMQ_DELETE_USER_DATA_Q}

# Management and observability properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh, prometheus
  endpoint:
    health:
      show-details: always
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: streamix
      deployment.environment: ${spring.profiles.active}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT}
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_ENDPOINT}

# Logging properties
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.streamix: DEBUG