# Local server configuration
server:
  port: 8111

# Local development configuration
spring:
  config:
    import:
      - optional:file:../env/dev.properties
  jpa:
    hibernate:
      ddl-auto: update

# Local logging configuration
logging:
  level:
    org.springframework.web: DEBUG
    com.mariuszilinskas.streamix: DEBUG